githubUser: parrot-mate
domain: pmate.chat
apps:
  - app: townhall
    dir: apps/townhall
    type: vite
    subdomain: townhall
    bucket: pmate-townhall-web
    repository: parrot-mate/felix-mono
  - app: blueprint-web
    dir: apps/blueprint-web
    type: vite
    subdomain: blueprint
    bucket: pmate-blueprint-web
    repository: parrot-mate/felix-mono
