name = "taskqueue"
type = "javascript" # Or "webpack" for older projects

account_id = "44dfd1cdd660ce949022ebb89b5df395"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-04"

kv_namespaces = [
  { binding = "TASK_KV", id = "5654add0646a4d8a8ac420f3c049e28f" }
]


[[queues.producers]]
queue = "task-asr-v1"
binding = "QUEUE_ASR"

[[queues.consumers]]
queue = "task-asr-v1"
type = "http_pull"

# --- 

[[queues.producers]]
queue = "task-tts-v1"
binding = "QUEUE_TTS"

[[queues.consumers]]
queue = "task-tts-v1"
type = "http_pull"

# ---

[[queues.producers]]
queue = "task-asr-rev-v1"
binding = "QUEUE_REVISE"

[[queues.consumers]]
queue = "task-asr-rev-v1"
type = "http_pull"



[[r2_buckets]]
binding = "TASK_R2"
bucket_name = "cache"

[[r2_buckets]]
binding = 'USER_R2'
bucket_name = 'users'

[observability.logs]
enabled = true
invocation_logs = false
