#!/bin/bash

app="v2ray"
# Define variables
LOG_FILE="$HOME/logs/$app.log"
PID_FILE="$HOME/logs/$app.pid"
BIN="/usr/local/bin/v2ray"
CONFIG="$HOME/.v2ray/jp.json"


case "$1" in
  start)
    if [ -f "$PID_FILE" ] && kill -0 $(cat "$PID_FILE") > /dev/null 2>&1; then
      echo "Process is already running."
      exit 1
    fi
    echo "Starting rev process..."
    nohup $BIN run --config $CONFIG > "$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    echo "$app started with PID $(cat $PID_FILE)."
    ;;

  stop)
    if [ -f "$PID_FILE" ]; then
      echo "Stopping $app process..."
      kill $(cat "$PID_FILE") && rm -f "$PID_FILE"
      echo "$app stopped."
    else
      echo "No $app process running."
    fi
    ;;

  log)
    tail -f "$LOG_FILE"
    ;;

  *)
    echo "Usage: $0 {start|stop|log}"
    exit 1
    ;;
esac
