name: I18n Translate

on:
  workflow_dispatch: # run manually
    inputs:
      keys:
        description: "Comma-separated keys to translate (leave empty for all)"
        required: false
        default: ""
      lang:
        description: "Language to translate (leave empty for all)"
        required: false
        default: ""
  push:
    branches:
      - main

jobs:
  translate:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout i18n-tools
        uses: actions/checkout@v4
        with:
          repository: parrot-mate/i18n-tools
          token: ${{ secrets.GH_TOKEN}}
          path: .github/actions/i18n-tools

      - name: Remove i18n-tools git metadata
        run: rm -rf .github/actions/i18n-tools/.git

      - name: Run i18n-tools
        uses: ./.github/actions/i18n-tools
        with:
          command: "translate"
          keys: ${{ github.event.inputs.keys }}
          token: ${{ secrets.GH_TOKEN }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
